### ISSUE TITLE
RC1

### ISSUE THREAD

**Issue by kristianolofsson** [fatuuse/hass-schoolsoft#1]
I get a RC1 using the script.

`sensor:
  - platform: command_line
    name: SchoolSoft
    json_attributes:
    - updated
    - icon
    - meal
    - student_0
    - schedule_0
    scan_interval: 14400
    command_timeout: 30
    command: "python3 /config/python_scripts/schoolsoft.py -u user -p pwd -s school"
    value_template: '{{ value_json.day | default("") }}'`

`Traceback (most recent call last):
  File "/config/python_scripts/schoolsoft.py", line 339, in <module>
    meals = api.fetch_lunch_menu(student=settings[0][0])
  File "/config/python_scripts/schoolsoft.py", line 123, in fetch_lunch_menu
    lunch_menu_grouped.append([lunch_menu[day],lunch_menu[day+1]])
IndexError: list index out of range
bash-5.1# 
`

**Comment by fatuuse** [comment]
Jag uppdaterade filen. Pröva den nya.

**Comment by fatuuse** [comment]
Du kan testa scriptet genom att bara köra python3 /config/python_scripts/schoolsoft.py -u user -p pwd -s school -l debug i shell eller liknande.

**Comment by kristianolofsson** [comment]
Debug:
`DEBUG:Try get: https://sms.schoolsoft.se/kmskola/jsp/student/right_parent_pwdadmin.jsp
DEBUG:Starting new HTTPS connection (1): sms.schoolsoft.se:443
DEBUG:https://sms.schoolsoft.se:443 "GET /kmskola/jsp/student/right_parent_pwdadmin.jsp HTTP/1.1" 302 0
DEBUG:https://sms.schoolsoft.se:443 "GET /kmskola/html/redirect_login.htm HTTP/1.1" 200 337
DEBUG:Server number: ('',)
DEBUG:Starting new HTTPS connection (1): sms.schoolsoft.se:443
DEBUG:https://sms.schoolsoft.se:443 "POST /kmskola/jsp/Login.jsp HTTP/1.1" 302 0
DEBUG:Save cookie in memory
DEBUG:Try get: https://sms.schoolsoft.se/kmskola/jsp/student/right_parent_pwdadmin.jsp
DEBUG:Starting new HTTPS connection (1): sms.schoolsoft.se:443
DEBUG:https://sms.schoolsoft.se:443 "GET /kmskola/jsp/student/right_parent_pwdadmin.jsp HTTP/1.1" 200 None
DEBUG:SchoolSoft logged in
DEBUG:RSS-link: ../public/right_public_parent_rss.jsp?key=624&key2=77d69bb37dfc1820ef1381e72131d453
DEBUG:RSS-link: ../public/right_public_parent_rss.jsp?key=631&key2=77d69bb37dfc1820ef1381e72131d453
DEBUG:Try get: https://sms.schoolsoft.se/kmskola/jsp/student/top_student.jsp?student=624
DEBUG:Starting new HTTPS connection (1): sms.schoolsoft.se:443
DEBUG:https://sms.schoolsoft.se:443 "GET /kmskola/jsp/student/top_student.jsp?student=624 HTTP/1.1" 302 0
DEBUG:https://sms.schoolsoft.se:443 "GET /kmskola/jsp/student/right_student_startpage.jsp HTTP/1.1" 200 None
DEBUG:SchoolSoft logged in
DEBUG:Try get: https://sms.schoolsoft.se/kmskola/jsp/student/right_parent_preschool_schedule_new.jsp?student=624&fromdate=2022-10-18
DEBUG:Starting new HTTPS connection (1): sms.schoolsoft.se:443
DEBUG:https://sms.schoolsoft.se:443 "GET /kmskola/jsp/student/right_parent_preschool_schedule_new.jsp?student=624&fromdate=2022-10-18 HTTP/1.1" 200 None
DEBUG:SchoolSoft logged in
DEBUG:Preschool time: 8:15 16:30
DEBUG:Preschool time: 8:15 16:30
DEBUG:Preschool time: 8:15 16:30
DEBUG:Preschool time: 8:15 16:30
DEBUG:Preschool time: 8:15 16:30
DEBUG:Try get: https://sms.schoolsoft.se/kmskola/jsp/student/right_student_schedule.jsp?menu=schedule&student=624
DEBUG:Starting new HTTPS connection (1): sms.schoolsoft.se:443
DEBUG:https://sms.schoolsoft.se:443 "GET /kmskola/jsp/student/right_student_schedule.jsp?menu=schedule&student=624 HTTP/1.1" 200 None
DEBUG:SchoolSoft logged in
DEBUG:Try get: https://sms.schoolsoft.se/kmskola/jsp/student/right_student_lunchmenu.jsp?menu=lunchmenu&student=624
DEBUG:Starting new HTTPS connection (1): sms.schoolsoft.se:443
DEBUG:https://sms.schoolsoft.se:443 "GET /kmskola/jsp/student/right_student_lunchmenu.jsp?menu=lunchmenu&student=624 HTTP/1.1" 200 None
DEBUG:SchoolSoft logged in
DEBUG:Menu raw:Pasta pesto med marinerade bönor
DEBUG:Menu raw:Köttbullar med kokt potatis brunsås lingon
DEBUG:Menu raw:Potatis&purjolökssoppa med hembakat bröd serveras med frukt
DEBUG:Menu raw:Helstekt kottlettrad med timjansky rostad potatis
DEBUG:Menu raw:Wokade nudlar med kyckling
Traceback (most recent call last):
  File "/config/python_scripts/schoolsoft.py", line 368, in <module>
    'meals_' + str(i) :api.fetch_lunch_menu(student=settings[0][i])}
  File "/config/python_scripts/schoolsoft.py", line 125, in fetch_lunch_menu
    lunch_menu_grouped.append([lunch_menu[day],lunch_menu[day+1]])
IndexError: list index out of range
`

**Comment by fatuuse** [comment]
https://github.com/fatuuse/hass-schoolsoft/commit/ab2fc98495b07edbcb16e5f815c283b3eab3551b
Testa nu.

**Comment by kristianolofsson** [comment]
Sorry, still the same error
`Traceback (most recent call last):
  File "/config/python_scripts/schoolsoft.py", line 370, in <module>
    {'student_'+ str(i) +'_id':settings[0][i],
IndexError: list index out of range
`

**Comment by fatuuse** [comment]
Snart funkar det nog. Jag hade klantat mig på ett ställe. 

Pröva ladda ner igen. 
Sedan börjar numreringen nu från student_1 osv
```
- platform: command_line
  name: SchoolSoft
  json_attributes:
  - updated
  - icon
  - meal
  - meals_1
  - student_1
  - student_2
  - student_3
  - preschool_1
  - preschool_2
  - preschool_3
  - schedule_1
  - schedule_2
  scan_interval: 21600 #6h
  command_timeout: 30
  command: python3 /config/script/schoolsoft.py -s school -u user -p password
  value_template: '{{ value_json.day | default("") }}'
```

**Comment by kristianolofsson** [comment]
Tested OK! Jag kommer testa mer men resultatet kommer iaf nu. Stort tack!

**Comment by fatuuse** [comment]
👍
